#!/usr/bin/env python3
"""
Script to update bundled baseline IoC data.

Run this before releases to ensure the bundled data is current:
    python scripts/update_baseline.py

Or with uv:
    uv run python scripts/update_baseline.py
"""

from __future__ import annotations

import json
import sys
from datetime import UTC, datetime
from pathlib import Path

import requests

IOC_URL = "https://raw.githubusercontent.com/tenable/shai-hulud-second-coming-affected-packages/main/list.json"
BASELINE_FILE = Path(__file__).parent.parent / "baseline_iocs.py"


def main() -> int:
    """Fetch current IoC data and update baseline_iocs.py."""
    print(f"Fetching IoC data from {IOC_URL}...")

    try:
        response = requests.get(IOC_URL, timeout=30)
        response.raise_for_status()
        data = response.json()
    except requests.RequestException as e:
        print(f"Error fetching IoC data: {e}", file=sys.stderr)
        return 1
    except json.JSONDecodeError as e:
        print(f"Error parsing JSON response: {e}", file=sys.stderr)
        return 1

    # Count packages
    if isinstance(data, dict):
        pkg_count = len(data)
    elif isinstance(data, list):
        pkg_count = len({entry.get("name") for entry in data if entry.get("name")})
    else:
        print(f"Unexpected data format: {type(data)}", file=sys.stderr)
        return 1

    # Format the data for Python
    version = datetime.now(UTC).strftime("%Y.%m.%d")

    # Pretty print the JSON for readability
    formatted_data = json.dumps(data, indent=4, sort_keys=True)

    content = f'''"""
Bundled baseline IoC data for offline operation.

This data is a snapshot and may be outdated. The scanner will attempt to
fetch fresh data from the network first.

To update this file with current IoC data, run:
    python scripts/update_baseline.py

Auto-generated by scripts/update_baseline.py
"""

from __future__ import annotations

# Version tag for the bundled data
BASELINE_IOC_VERSION = "{version}"

# Format: {{"package-name": {{"vuln_vers": ["v1", "v2"]}}}}
BASELINE_COMPROMISED_PACKAGES: dict[str, dict[str, list[str]]] = {formatted_data}
'''

    BASELINE_FILE.write_text(content)
    print(f"Updated {BASELINE_FILE}")
    print(f"Version: {version}")
    print(f"Packages: {pkg_count}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
